//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtdelKadrov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public int Id_Sotrudnik { get; set; }
        public string Table_Number { get; set; }
        public string FIO { get; set; }
        public int Id_Otdel { get; set; }
        public int Id_Dolzhnost { get; set; }
    
        public virtual Dolzhnost Dolzhnost { get; set; }
        public virtual Otdel Otdel { get; set; }
    }
}
